### ISSUE TITLE
Mod 0 Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [EmilyLalonde/mod_0_skills#1]
# Checklist/Rubric

#### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub
* [x]  Directories are named correctly.
* [x]  Files are named correctly.
* [x]  Files and directories are structured correctly.
* [x]  Initial commit was made.
* [x]  Initial commit was pushed to GitHub.

#### Part II: Top Down Design
* [x]  Larger processes were broken into smaller layers.
* [x]  Changes were added and committed with a properly formatted commit message starting with a verb and a capital letter.
* [x]  Changes were pushed to Github.

#### Part III: Classes in a System
* [ ]  Directories and files were named and structured correctly.
* [x]  The attributes chosen for **Class #1** represent states or characteristics.
* [x]  The attributes chosen for **Class #2** represent states or characteristics.
* [x]  The attributes chosen for **Class #3** represent states or characteristics.
* [x]  The methods chosen for **Class #1** represent behaviors or actions.
* [x]  The methods chosen for **Class #2** represent behaviors or actions.
* [x]  The methods chosen for **Class #3** represent behaviors or actions.
* [ ]  Data type (string, integer, boolean, array, hash/object, datetime) were identified for each attribute in all three classes.
* [x]  Individual changes were added and committed separately with a properly formatted commit message.
* [x]  Changes were pushed to Github.

**Mod 0 Technical Assessment Results**

* [ ]   Technical Ready
* [x]   Pending
* [ ]   Not Ready

**Comment by timomitchel** [comment]
Good job on the assessment @EmilyLalonde. I want you to make a few changes, and then you will be `Technical Ready`. This is minor, but directory structure is important. Please create a `classes` directory and put your class files into that directory. Commit this change and push to Github with a properly formatted commit message. Make sure that **all** of your classes are named singularly and not plurally.  Go over a few of your attributes and think about if there are better data-types or changes you can think of. For one example: `Rating` would probably be a float and it would probably take a calculation of the average of all ratings to return that values. It could be an array of all `Ratings`, but then it would need to be called `Ratings` plurally. If we're thinking in terms of an app, class 2 would be better named `Cart` to follow the convention set by other ordering apps. Menu Items could be a string, but an array would make more sense here. Order Total is definitely close, but because it probably wouldn't result in a whole number every time, float is a better data-type in this situation. Class 3 looks good, but we would want to change `Order history` to `Orders` if it's going to be an array. Go ahead and make these changes and send Rachel and I a DM when the repo is updated to reflect them.
